title: Data + Donuts Boston
description: Changing local government from the ground up.
email: "info@datadonuts.boston"
event_label: Events
# Publish posts or collection documents with a future date.
future: true
github: "mcplanner/data-donuts-boston"
permalink: /event/:title.html
source: ./src
timezone: America/New_York
url: "https://datadonuts.boston"
